version: '2.3'

services:
  spiderfoot:
    build: spiderfoot/.
    container_name: spiderfoot
    restart: always
    ports:
     - "8081:8080"
    image: "dtagdevsec/spiderfoot:2006"
    volumes:
     - ./spiderfoot/data/spiderfoot.db:/home/spiderfoot/spiderfoot.db
  gvm:
    build: gvm/.
    container_name: gvm
    restart: always
    ports:
      - "8080:9392"
    image: "securecompliance/gvm:latest"
    environment: 
      - PASSWORD="PW"
    volumes:
      - gvm-data:/data
  serpico:
    environment:
      - SRP_ADMIN=administrator
      - SRP_FINDINGS=yes
    build:
      dockerfile: serpico/docker/dev.dockerfile
      context: .
    image: "serpico/serpico:latest"
    container_name: serpico
    ports:
      - "8443:8443"
    volumes:
      - serpico:/Serpico
  gophish:
    image: "gophish/gophish:latest"
    ports:
      - "3333:3333"
      - "80:80"
volumes:
  gvm-data:
  serpico:
