version: '2.3'

services:
  elasticsearch:
    build: elasticsearch/.
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    image: constantinti/elasticsearch:latest
    environment:
     - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
    volumes:
      - ./elasticsearch/data:/data
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.10.1
    ports:
      - "5601:5601"
  suricata:
    build: suricata/.
    container_name: suricata
    restart: always
    environment:
    # For ET Pro ruleset replace "OPEN" with your OINKCODE
     - OINKCODE=OPEN
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
    image: "constantinti/suricata:latest"
    volumes:
     - ./suricata/log:/var/log/suricata
  filebeat:
    build: filebeat/.
    container_name: filebeat
    image: "constantinti/filebeat:latest"
    volumes:
      - ./suricata/log:/suricata
